# Generated by Django 4.0.4 on 2022-05-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_search', models.TextField(blank=True)),
                ('where_search', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Skills_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skil', models.CharField(max_length=16, unique=True)),
                ('how_many_skil', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('salary', models.CharField(max_length=32)),
                ('about', models.TextField(blank=True)),
                ('link', models.TextField(unique=True)),
                ('skils', models.ManyToManyField(to='parserapp.skills_table')),
            ],
        ),
    ]
