# Generated by Django 4.0.5 on 2022-06-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='link',
            field=models.TextField(blank=True, verbose_name='Link'),
        ),
    ]
