# Generated by Django 4.0.4 on 2022-05-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0002_alter_vacancy_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills_table',
            options={'ordering': ('skil',)},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ('link',)},
        ),
        migrations.RemoveField(
            model_name='params',
            name='where_search',
        ),
    ]
