# Generated by Django 4.0.4 on 2022-05-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserapp', '0003_alter_skills_table_options_alter_vacancy_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills_table',
            name='how_many_skil',
        ),
        migrations.AddField(
            model_name='params',
            name='where_search',
            field=models.CharField(default=2, max_length=32),
            preserve_default=False,
        ),
    ]
